@host = http://localhost:4000/api/v1
@contentType = application/json
@authToken = your_bearer_token_here

### Register
# @name register
POST {{host}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Test User",
  "email": "longdevlor133214@gmail.com",
  "password": "3110@Long!!"
}

### Login
# @name login
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
  "email": "longdevlor@gmail.com",
  "password": "123@Long!!"
}

### Get me (current user) - cần token
GET {{host}}/auth/me
Authorization: Bearer {{authToken}}
