@host = http://localhost:4000/api/v1
@contentType = application/json
@authToken = your_bearer_token_here
@roleId = 019c2cca-0000-7842-93ce-f326abd8e36b
@permissionId = 019c2cca-0000-7842-93ce-000000000001

### List roles (search, sort_by, limit)
GET {{host}}/roles?search=admin&sort_by=name:asc&limit=20
Authorization: Bearer {{authToken}}

### Create role
POST {{host}}/roles
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "name": "Editor"
}

### Get role by ID
GET {{host}}/roles/{{roleId}}
Authorization: Bearer {{authToken}}

### Update role
PATCH {{host}}/roles/{{roleId}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "name": "Senior Editor"
}

### Delete role
DELETE {{host}}/roles/{{roleId}}
Authorization: Bearer {{authToken}}

### Get permissions of role
GET {{host}}/roles/{{roleId}}/permissions
Authorization: Bearer {{authToken}}

### Assign permission to role
POST {{host}}/roles/{{roleId}}/permissions/{{permissionId}}
Authorization: Bearer {{authToken}}

### Revoke permission from role
DELETE {{host}}/roles/{{roleId}}/permissions/{{permissionId}}
Authorization: Bearer {{authToken}}
